// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/sync-dsh-runtime-baseline.mjs. Do not edit directly.

export const DSH_RUNTIME_VERSION = "0.1.3-alpha.1" as const;
export const DSH_RUNTIME_TAG = "dsh-v0.1.3-alpha.1" as const;
export const DSH_RUNTIME_COMMIT = "d347e703725e7e2954a82b08cc00410c7f275c21" as const;
