// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/sync-dsh-runtime-baseline.mjs. Do not edit directly.

enum DSHRuntimeBaseline {
    static let version = "0.1.3-alpha.1"
    static let tag = "dsh-v0.1.3-alpha.1"
    static let commit = "d347e703725e7e2954a82b08cc00410c7f275c21"
}
