import sharp from 'sharp';
import { describe, expect, it, vi } from 'vitest';

import type { GeometryNode } from '../../../src/drawing/index.js';
import type { CleanLineVectorizationResult } from '../drawing-vectorization/types.js';
import { DrawingRegionRedrawService } from './redraw-service.js';
import type { DrawingRegionImageEditProvider } from './types.js';

async function png(width = 100, height = 80): Promise<Buffer> {
  return sharp({
    create: { width, height, channels: 4, background: { r: 255, g: 255, b: 255, alpha: 1 } },
  }).png().toBuffer();
}

function vectorization(sourceId: string): CleanLineVectorizationResult {
  return {
    sourceId, pipelineVersion: 'generated-fixture-v1', width: 100, height: 80,
    analysisScale: 1, medianLineWidthPx: 2,
    chains: [
      {
        id: 'chain_0123456789abcdef0123', closed: false,
        samples: [[10, 10], [30, 10]], simplified: [[10, 10], [30, 10]],
        bounds: { x: 10, y: 10, width: 20, height: 0.5 },
        pieces: [piece('piece_line', [[10, 10], [30, 10]], {
          type: 'line', parameters: { start: [10, 10], end: [30, 10] },
          fitErrorMean: 0, fitErrorP95: 0, fitErrorMax: 0, confidence: 0.98,
        })],
        segmentation: segmentation(),
      },
      {
        id: 'chain_abcdef0123456789abcd', closed: false,
        samples: [[40, 20], [45, 30], [50, 20]], simplified: [[40, 20], [45, 30], [50, 20]],
        bounds: { x: 40, y: 20, width: 10, height: 10 },
        pieces: [piece('piece_polyline', [[40, 20], [45, 30], [50, 20]], null)],
        segmentation: segmentation(),
      },
      {
        id: 'chain_fedcba9876543210fedc', closed: false,
        samples: [[90, 70], [99, 79]], simplified: [[90, 70], [99, 79]],
        bounds: { x: 90, y: 70, width: 9, height: 9 },
        pieces: [piece('piece_outside', [[90, 70], [99, 79]], null)],
        segmentation: segmentation(),
      },
    ],
  };
}

describe('DrawingRegionRedrawService', () => {
  it('persists generated bytes once, vectorizes them and projects only authorized geometry to world space', async () => {
    const generated = await png();
    const provider: DrawingRegionImageEditProvider = {
      edit: vi.fn(async () => ({ png: generated, providerRequestId: 'provider_1' })),
    };
    const put = vi.fn(async () => ({
      sourceId: 'source_0123456789abcdef01234567', sha256: 'a'.repeat(64),
      mimeType: 'image/png' as const, byteLength: generated.byteLength, page: 1,
    }));
    const vectorizeSource = vi.fn(async ({ sourceId }: { sourceId: string }) => {
      const result = vectorization(sourceId);
      return {
        ...result,
        chains: result.chains.map((chain) => ({
          ...chain,
          evidence: {
            handle: `evidence_${chain.id}`, sourceId, regionId: `vector_${chain.id}`,
            kind: chain.pieces[0].candidate ? 'line-candidate' as const : 'polyline-candidate' as const,
            bounds: chain.bounds, confidence: chain.pieces[0].candidate?.confidence ?? 0.8,
            touchesRegionEdge: false, sampleCount: chain.samples.length,
          },
        })),
      };
    });
    const service = new DrawingRegionRedrawService({
      provider,
      sourceArtifacts: { put, read: vi.fn() },
      vectorization: { vectorizeSource },
    });
    const crop = await png();

    const result = await service.redraw({
      prompt: '添加卷发', cropPng: crop, maskPng: crop, protectedMaskPng: crop,
      seed: 23, signal: new AbortController().signal, deadlineAt: Date.now() + 10_000,
      cropPixelToWorld: [1, 0, 0, -1, 100, 200],
      authorizedContours: [[[105, 115], [160, 115], [160, 195], [105, 195]]],
      authorizedHoles: [], maxPixels: 100_000,
    });

    expect(put).toHaveBeenCalledTimes(1);
    expect(put).toHaveBeenCalledWith({ data: generated.toString('base64'), mimeType: 'image/png', page: 1 });
    expect(vectorizeSource).toHaveBeenCalledWith(expect.objectContaining({
      sourceId: 'source_0123456789abcdef01234567', maxPixels: 100_000,
    }));
    expect(result.generatedSource.sourceId).toBe('source_0123456789abcdef01234567');
    expect(result.providerRequestId).toBe('provider_1');
    expect(result.geometry.map((node: GeometryNode) => node.type)).toEqual(['line', 'polyline']);
    expect(result.geometry[0]).toMatchObject({ start: [110, 190], end: [130, 190] });
    expect(result.geometry[1]).toMatchObject({
      vertices: [{ point: [140, 180] }, { point: [145, 170] }, { point: [150, 180] }],
    });
    expect(JSON.stringify(result)).not.toContain(generated.toString('base64'));
  });

  it('does not persist or vectorize a failed generation', async () => {
    const provider: DrawingRegionImageEditProvider = {
      edit: async () => { throw new Error('provider failed'); },
    };
    const put = vi.fn();
    const vectorizeSource = vi.fn();
    const service = new DrawingRegionRedrawService({
      provider,
      sourceArtifacts: { put, read: vi.fn() },
      vectorization: { vectorizeSource },
    });
    const image = await png();

    await expect(service.redraw({
      prompt: '重绘', cropPng: image, maskPng: image, protectedMaskPng: image,
      seed: 1, signal: new AbortController().signal, deadlineAt: Date.now() + 10_000,
      cropPixelToWorld: [1, 0, 0, -1, 0, 80],
      authorizedContours: [[[0, 0], [100, 0], [100, 80], [0, 80]]],
      authorizedHoles: [], maxPixels: 100_000,
    })).rejects.toThrow('provider failed');
    expect(put).not.toHaveBeenCalled();
    expect(vectorizeSource).not.toHaveBeenCalled();
  });
});

function piece(
  id: string,
  simplified: Array<readonly [number, number]>,
  candidate: import('../drawing-vectorization/types.js').CleanLinePrimitiveCandidate | null,
) {
  const xs = simplified.map((point) => point[0]);
  const ys = simplified.map((point) => point[1]);
  return {
    id,
    sampleRange: [0, simplified.length - 1] as [number, number],
    wraps: false,
    closed: false,
    simplified,
    bounds: {
      x: Math.min(...xs), y: Math.min(...ys),
      width: Math.max(...xs) - Math.min(...xs),
      height: Math.max(...ys) - Math.min(...ys),
    },
    candidate,
  };
}

function segmentation() {
  return {
    algorithmVersion: 'adaptive-multiscale-v1', drawingDiagonalPx: 128,
    chainLengthPx: 20, fitTolerancePx: 1, nearWindowPx: 2, farWindowPx: 4,
    minimumSpanPx: 4, splitPenalty: 1.5, decisions: [],
  };
}
